name: explore
description: The Adityas chart explorer.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  arrow_options:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: da6b453d2d358975602a57dfedfa49f0568b2116
      path: arrow/options
  arrow_swe:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: da6b453d2d358975602a57dfedfa49f0568b2116
      path: arrow/swe
  arrow_core:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: da6b453d2d358975602a57dfedfa49f0568b2116
      path: arrow/core
  arrow_calc:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: da6b453d2d358975602a57dfedfa49f0568b2116
      path: arrow/calc
  charts_dart:
    git:
      url: https://github.com/ninthhousestudios/charts_dart
  swisseph_rs: ^0.2.1
  web: ^1.1.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.4
  file_picker: ^8.1.6
  flutter_svg: ^2.0.17
  http: ^1.6.0
  supabase_flutter: ^2.15.0
  sentry_flutter: ^9.22.0

dependency_overrides:
  swisseph_rs:
    path: /home/josh/nhs/soft/astrology/swisseph.rs.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/beings/
    - assets/images/emblems/
    - assets/images/planets/
    - assets/ephe/
    - assets/glyphs/
    - assets/glyphs/beings/
    - assets/glyphs/planets/
    - assets/text/
