name: explore
description: The Adityas chart explorer.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  arrow_options:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: 0b3f3015a7ff93f69a97862c69755c24d0b053a2
      path: arrow/options
  arrow_swe:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: 0b3f3015a7ff93f69a97862c69755c24d0b053a2
      path: arrow/swe
  arrow_core:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: 0b3f3015a7ff93f69a97862c69755c24d0b053a2
      path: arrow/core
  arrow_calc:
    git:
      url: https://github.com/ninthhousestudios/arjuna
      ref: 0b3f3015a7ff93f69a97862c69755c24d0b053a2
      path: arrow/calc
  swisseph: ^0.5.1
  web: ^1.1.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.4
  file_picker: ^8.1.6
  toml: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ephe/
